name: Gh-Pages - Portfolio Website Flutter

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: 3.16.5
          flutter-version: 3.22.2
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build web
      #   run: flutter build web --web-renderer canvaskit --release

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: build/web
      #     base_href: /flutter_portfolio/

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /flutter_portfolio/
          webRenderer: html
# References
# https://github.com/codetricity/dot_guide_pano/blob/main/.github/workflows/gh-pages.yaml
# https://github.com/subosito/flutter-action
# https://github.com/bluefireteam/flutter-gh-pages
