name: Gh-Pages - Portfolio Website Flutter

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.16.5
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      # - name: Verify Flutter version
      #   run: flutter --version

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build Flutter web app
      #   run: flutter build web --web-renderer canvaskit

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /flutter_portfolio/
          webRenderer: canvaskit
# References
# https://github.com/codetricity/dot_guide_pano/blob/main/.github/workflows/gh-pages.yaml
# https://github.com/subosito/flutter-action
# https://github.com/bluefireteam/flutter-gh-pages
