name: Gh-Pages - Portfolio Website Flutter

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /flutter_portfolio/
          webRenderer: canvaskit
# References
# https://github.com/codetricity/dot_guide_pano/blob/main/.github/workflows/gh-pages.yaml
# https://github.com/subosito/flutter-action
# https://github.com/bluefireteam/flutter-gh-pages
